Update test.yml

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -17,11 +17,11 @@ jobs:
       shell: bash
       run: |
         mkdir -p test-cache
-        dd if=/dev/urandom of=test-cache/file.txt count=1024 bs=1048576
+        dd if=/dev/urandom of=test-cache/file.txt count=2048 bs=1048576
     - name: Save cache
       uses: dhadka/cache@azure-blob-client
       with:
-        key: test-large-${{ runner.os }}-${{ github.run_id }}
+        key: test-large2-${{ runner.os }}-${{ github.run_id }}
         path: test-cache
   test-restore:
     needs: test-save
@@ -36,7 +36,7 @@ jobs:
     - name: Restore cache
       uses: dhadka/cache@azure-blob-client
       with:
-        key: test-large-${{ runner.os }}-${{ github.run_id }}
+        key: test-large2-${{ runner.os }}-${{ github.run_id }}
         path: test-cache
     - name: Verify cache files in working directory
       shell: bash
@@ -45,9 +45,27 @@ jobs:
             echo "Files not found"
             exit 1
         fi
-        #size=$(du -b test-cache/file.txt | awk '{print $1}')
-        #expected="157286400"
-        #if [ "$size" != "$expected" ]; then
-        #  echo "Invalid cache size. Was $size, expected $expected"
-        #  exit 1
-        #fi
+  test-restore-old:
+    needs: test-save
+    strategy:
+      matrix:
+        os: [ubuntu-latest, windows-latest, macOS-latest]
+      fail-fast: false
+    runs-on: ${{ matrix.os }}
+    steps:
+    - name: Checkout
+      uses: actions/checkout@v2
+    - name: Restore cache
+      uses: dhadka/cache@azure-blob-client
+      env:
+        DISABLE_AZURE_SDK: true
+      with:
+        key: test-large2-${{ runner.os }}-${{ github.run_id }}
+        path: test-cache
+    - name: Verify cache files in working directory
+      shell: bash
+      run: |
+        if [ ! -f test-cache/file.txt ]; then
+            echo "Files not found"
+            exit 1
+        fi
