Update test.yml

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -31,14 +31,12 @@ jobs:
     - name: Validate cache
       if: steps.cache.outputs.cache-hit == 'true'
       run: |
-        ls -al ~
-        #foobar
-        #size=$(du -b ~/cache-folder/file.txt | awk '{print $1}')
-        #expected="157286400"
-        #if [ "$size" != "$expected" ]; then
-        #  echo "Invalid cache size. Was $size, expected $expected"
-        #  exit 1
-        #fi
+        size=$(du -b ~/cache-folder/file.txt | awk '{print $1}')
+        expected="157286400"
+        if [ "$size" != "$expected" ]; then
+          echo "Invalid cache size. Was $size, expected $expected"
+          exit 1
+        fi
         
         time_diff="$(( ${{ steps.stop-time.outputs.time }} - ${{ steps.start-time.outputs.time }} ))"
         time_limit=20
